language: scala

scala:
  - 2.12.3

script:
  - >-
    sbt
    ++$TRAVIS_SCALA_VERSION
    scalafmt::test
    test:scalafmt::test
    sbt:scalafmt::test
    test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
